# Generated by Django 2.0.1 on 2018-02-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=250)),
                ('credits', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Courses')),
            ],
        ),
    ]
