# Generated by Django 2.0.1 on 2018-02-07 02:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('music', '0003_auto_20180207_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
