# Generated by Django 2.0.1 on 2018-02-07 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180207_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Album')),
            ],
        ),
    ]
