# Generated by Django 2.0.1 on 2018-02-25 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0008_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='attendee',
            field=models.ForeignKey(blank=True, db_column='attendee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_attendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
