# Generated by Django 2.0.1 on 2018-02-25 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_appointments_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_attendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
